# Generated by Django 5.1 on 2024-08-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('av_status', models.BooleanField()),
                ('av_name', models.CharField(max_length=255)),
                ('av_version', models.CharField(max_length=50)),
                ('av_up_to_date', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['hostname', 'timestamp'], name='client_heal_hostnam_d639e5_idx')],
            },
        ),
    ]
