# Generated by Django 5.1 on 2024-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AVPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av_name', models.CharField(max_length=255)),
                ('min_version', models.CharField(max_length=50)),
                ('assigned_vlan', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'AV Policies',
                'ordering': ['av_name', 'min_version'],
            },
        ),
        migrations.AddField(
            model_name='clienthealth',
            name='assigned_vlan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
