# Generated by Django 5.1 on 2024-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_health', '0002_avpolicy_clienthealth_assigned_vlan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthealth',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
